# Generated by Django 4.2.6 on 2024-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=70)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact_person_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('mobile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('address', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('aadhar_card', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
            ],
        ),
    ]
